
// This file is automatically generated. Do not edit it directly.
import { supabase, checkSupabaseConnection } from '@/lib/supabase';

// Re-export the same client instance from lib/supabase
export { supabase, checkSupabaseConnection };

// Add debug logging
console.log('Supabase client re-exported from integrations/supabase/client.ts');

// Verify connection
checkSupabaseConnection().then(isConnected => {
  console.log('Supabase connection check from integrations module:', isConnected);
});
